#!/bin/sh
# rescshri 1.2 init

export HOME=/home
export PATH=/bin:/sbin:/usr/bin

mountpoint -q proc || mount -t proc proc proc
mountpoint -q sys || mount -t sysfs sys sys

dmesg -n 1

if ! mountpoint -q dev
then
  mount -t devtmpfs dev dev || mdev -s
  mkdir -p dev/pts
  mountpoint -q dev/pts || mount -t devpts dev/pts dev/pts
fi

hostname rescshri

[ -z "$CONSOLE" ] &&
  CONSOLE="$(sed -n 's@.* console=\(/dev/\)*\([^ ]*\).*@\2@p' /proc/cmdline)"

[ -z "$HANDOFF" ] && HANDOFF=/bin/sh && rescshri
[ -z "$CONSOLE" ] && CONSOLE=console

exec /sbin/oneit -c /dev/"$CONSOLE" $HANDOFF


