#!/bin/sh

    LD='/usr/share/livedemo';

    FHDD="$LD/hdd/hda.img"

    resinit () {

        losetup --partscan --show --find $FHDD > /dev/null 2>&1

        ln -n /dev/loop0 /dev/hda > /dev/null 2>&1
        for i in 1 2 3 4 5
        do
            ln -n /dev/loop0p$i /dev/hda$i > /dev/null 2>&1
        done
    }

    resdenit () {

        rm /dev/hda > /dev/null 2>&1
        for i in 1 2 3 4 5
        do
            rm /dev/hda$i > /dev/null 2>&1
        done	

        losetup -d /dev/loop0 > /dev/null 2>&1
        sleep 1

        resinit
    }


    hdd_image () {
        printf "Setting up virtual hard disk storage /dev/hda ."
        dd if=/dev/zero of=$FHDD bs=1024 count=6144 > /dev/null 2>&1
        printf "."
        printf "n\np\n\n\n\nw\n" | $LD/bin/fdisk $FHDD > /dev/null 2>&1
        printf "."
        resinit
        printf "."
	mkfs.ext4 /dev/loop0p1 > /dev/null 2>&1
        printf "."
        resdenit
	printf ". "
        printf "done.\n"
        sleep 1
    }


